- name: Setup apache
  hosts: webserver
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed

- name: Setup tomcat
  hosts: appserver
  tasks:
  - name: install httpd
    yum:
      name: tomcat
      state: installed
